services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'user_db'
      MYSQL_ROOT_PASSWORD: 'user123'
      MYSQL_USER: 'user_user'
      MYSQL_PASSWORD: 'user123'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - demo_net
  spring-demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_DBNAME=user_db
      - DB_USER=user_user
      - DB_PASSWORD=user123
    networks:
      - demo_net
    restart: unless-stopped
    depends_on:
      - db

volumes:
  my-db:

networks:
  demo_net:
    driver: bridge
